### ISSUE TITLE
Link to "Taxi Data Stream instructions" is broken

### ISSUE THREAD

**Issue by brakmic** [dataArtisans/flink-training#13]
Hi,

Just found a small issue on http://dataartisans.github.io/flink-training/exercises/rideCleansing.html

Under the accordeon entry  **Obtaining a Taxi Ride Data Stream** the link to **Taxi Data Stream instructions** is broken: 

``` html
http://dataartisans.github.io/flink-training/exercises/taxtData.html
```

Probably, it should be 

``` html
http://dataartisans.github.io/flink-training/exercises/taxiData.html
```

**Comment by mxm** [comment]
Thank you! I corrected the link.
