### ISSUE TITLE
Add a Gelly task

### ISSUE THREAD

**Issue by vasia** [dataArtisans/flink-training#3]
Hi there artisans,

does this repo accept contributions? :D 

@samk3211 has started working on Gelly and we are thinking of adding one graph task to this training.
Our idea is to take the edges of the reply-to graph, merge the duplicate nodes, create a graph and run a weighted PageRank algorithm on it.
What do you think about this?
Can you please give her some pointers on what she needs to add?
Slides, description on the website, sample code?

Thank you!

**Comment by fhueske** [comment]
Certainly, contributions are highly welcome!
A Gelly exercise would be a nice thing to have :-)

I think we can start adding the exercise and work on the slides later.
For an exercise, we need reference implementations in Java (and Scala once Gelly is available for Scala), an exercise description (preferable along the lines of the other descriptions) and add it to the exercise overview.

**Comment by samk3211** [comment]
Hi! 
I have opened a new PR. A reference solution in Java and exercise description have been added.
